apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linux-server
  template:
    metadata:
      labels:
        app: linux-server
    spec:
      containers:
      - name: linux-server
        image: ubuntu:latest  # Replace with the specific Linux image you want to use
        ports:
        - containerPort: 80
        command: ["/bin/bash", "-c", "while true; do sleep 3600; done"] # Keeps the container running